version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: cc_postgres
    environment:
      POSTGRES_USER: cc
      POSTGRES_PASSWORD: cc_password
      POSTGRES_DB: creative_construct
    ports:
      - "5432:5432"
    volumes:
      - cc_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cc_redis
    ports:
      - "6379:6379"
    volumes:
      - cc_redis:/data

volumes:
  cc_pg:
  cc_redis:
